# CI workflow to build application using Maven Wrapper

name: Java CI with Maven Wrapper

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  JAVA_VERSION: '17'

jobs:

  build:
    timeout-minutes: 10
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify --file pom.xml
