# CI workflow to build application using Maven Wrapper

name: Java CI with Maven Wrapper

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  JAVA_VERSION: '17'

jobs:

  build:
    timeout-minutes: 10
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify --file pom.xml
