# CI workflow to build application using Maven Wrapper

name: Java CI with Maven Wrapper

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  JAVA_VERSION: '17'

jobs:

  build:
    timeout-minutes: 10
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Set up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify --file pom.xml
