# workflow to run terraform plan on Dev

name: Terraform plan

on:
  pull_request:
    branches:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_REGION: 'eu-west-1'
  AWS_ROLE: '' # TODO Fill in the role to assume for your deployment
  TF_DIR: '' # TODO Fill in the terraform directory for your deployment
  NODE_VERSION: 'lts/*'

jobs:
  terraform:
    name: Terraform plan
    runs-on: self-hosted
    timeout-minutes: 5

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_DIR }}

    permissions:
      contents: read
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
