# workflow to run terraform plan on Dev

name: Terraform plan

on:
  pull_request:
    branches:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_REGION: 'eu-west-1'
  AWS_ROLE: '' # TODO Fill in the role to assume for your deployment
  TF_DIR: '' # TODO Fill in the terraform directory for your deployment
  NODE_VERSION: 'lts/*'

jobs:
  terraform:
    name: Terraform plan
    runs-on: self-hosted
    timeout-minutes: 5

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_DIR }}

    permissions:
      contents: read
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
