# workflow to run terraform plan on Dev

name: Terraform plan

on:
  pull_request:
    branches:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_REGION: 'eu-west-1'
  AWS_ROLE: '' # TODO Fill in the role to assume for your deployment
  TF_DIR: '' # TODO Fill in the terraform directory for your deployment
  NODE_VERSION: 'lts/*'

jobs:
  terraform:
    name: Terraform plan
    runs-on: self-hosted
    timeout-minutes: 5

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_DIR }}

    permissions:
      contents: read
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
