name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LOG_LEVEL: debug

jobs:
  validate-config:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        file:
          - default
          - renovate-config
          - frontend
          - automerge
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Setup Node.js environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: '18'

      - name: testing ${{ matrix.file }}
        run: npx -p renovate -c renovate-config-validator
